import "./globals.css";
// import {Roboto } from "next/font/google";
import {Work_Sans} from "next/font/google";

const workSans = Work_Sans({
  subsets:['latin'],
  weight: ['400', '500', '700']
})

// const roboto = Roboto({
//   subsets:['latin'],
//   weight: ['400', '500', '700']
// })
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={roboto.className}> */}
      <body className={workSans.className}>
        {children}
      </body>
    </html>
  );
}
