import "./globals.css";
import {Roboto } from "next/font/google";
import {Work_Sans} from "next/font/google";

const workSans = Work_Sans({
  subsets:['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-work-sans'
})

const roboto = Roboto({
  subsets:['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto'
})
export const metadata = {
  title: "My App",
  description: "Generated by create next app",
  icons: {
    icon: "/file.svg",  
  }
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={roboto.className}> */}
      {/* <body className={workSans.className}> */}
      <body className={`${workSans.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
